<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="63523" started-at="2018-07-17T20:52:23Z" finished-at="2018-07-17T20:53:26Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="63523" started-at="2018-07-17T20:52:23Z" finished-at="2018-07-17T20:53:26Z">
      <class name="test.RegisterTest">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:test.RegisterTest@18be83e4]" name="beforeClass" is-config="true" duration-ms="26334" started-at="2018-07-17T20:52:23Z" finished-at="2018-07-17T20:52:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="checkOpenRegistrationBoxNewWindow()[pri:1, instance:test.RegisterTest@18be83e4]" name="checkOpenRegistrationBoxNewWindow" duration-ms="14753" started-at="2018-07-17T20:52:49Z" finished-at="2018-07-17T20:53:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkOpenRegistrationBoxNewWindow -->
        <test-method status="PASS" signature="enterExistingUserRegistrationData()[pri:2, instance:test.RegisterTest@18be83e4]" name="enterExistingUserRegistrationData" duration-ms="10322" started-at="2018-07-17T20:53:04Z" depends-on-methods="test.RegisterTest.checkOpenRegistrationBoxNewWindow" finished-at="2018-07-17T20:53:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enterExistingUserRegistrationData -->
        <test-method status="FAIL" signature="enterLogin()[pri:3, instance:test.RegisterTest@18be83e4]" name="enterLogin" duration-ms="10094" started-at="2018-07-17T20:53:14Z" depends-on-methods="test.RegisterTest.enterExistingUserRegistrationData" finished-at="2018-07-17T20:53:25Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at test.RegisterTest.enterLogin(RegisterTest.java:61)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enterLogin -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:test.RegisterTest@18be83e4]" name="afterClass" is-config="true" duration-ms="1971" started-at="2018-07-17T20:53:25Z" finished-at="2018-07-17T20:53:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- test.RegisterTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
